### ISSUE TITLE
Limit in displayed nodes?

### ISSUE THREAD

**Issue by a4ng3l** [Microsoft/PowerBI-visuals-NetworkNavigator#24]
From my early tests it seems that only a limited amount of nodes are drawn in the visualization. Is there a hard limit in the number of items that can be displayed?
Some context;
I would like to display about 80k items in the framework of data migration.
My idea is to show sources tables, destination tables and the scripts that link them -that amounts to 80k nodes. I cannot simplify the data -I need the full data to cluster the tables / scripts to orchestrate a migration. 
Can someone point me to a workaround?

**Comment by stopyoukid** [comment]
Yes, the amount is limited to whatever PowerBI gives by default, which I believe is 1000.

There are a couple of issues:
- That is a lot of data to pull down from PowerBI (specifically PowerBI web), it would take a not insignificant amount of time.
- Rendering that many nodes would be prohibitively slow.

As for workarounds, there are no straight forward ones, but you do have a couple of options:
- Create a custom build which pulls down the required number of nodes by forking the repo and adding `"dataReductionAlgorithm": { "window": { "count": 80000 } }` to the rows property here: https://github.com/Microsoft/PowerBI-visuals-NetworkNavigator/blob/develop/packages/network-navigator-powerbi/src/capabilities.ts#L45.  You would also need to change the `projectId` here - https://github.com/Microsoft/PowerBI-visuals-NetworkNavigator/blob/develop/packages/network-navigator-powerbi/src/build.json#L6
- Set up your reports/dashboard to be filter based, so that whenever any filter is selected, the # of nodes in the network navigator is < 1000.  For example, based on your information, have a slicer that has a list of "source tables", and then when you select a source table, it filters the network navigator to the connections around the selected source table.
